config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout', password: 'password', confirmation: 'confirmation', unlock: 'unlock', registration: 'account', sign_up: 'register' }

  resources :albums do
    get '/search', to: 'albums#search', on: :collection
    get '/mine', to: 'albums#mine', on: :collection
  end

  resources :artists

  root to: "marketing#index"
end

app/models/artist.rb
class Artist < ApplicationRecord
  require 'csv'
  
  has_many :albums
  
  validates :name, presence: true
  
  def albums_years
    years = self.albums.map {|a| a.year if a.published.present? }.compact
    years.any? ? "#{years.min}-#{years.max}" : 'N/A'
  end
  
  def common_words
    string = ''
    self.albums.each do |album|
      album.tracks.each do |track|
        string += " #{track.name}"
      end
    end
    words = string.split(' ').reject(&:empty?)
    counts = words.inject(Hash.new(0)) { |h,v| h[v] += 1; h }
    max = counts.values.max
    counts.select { |k,v| v == max }.keys.to_sentence
  end
  
  def self.export_columns
    ['name', '# of Albums', 'Years', 'Common Words']
  end
  
  def self.to_csv(options = {})
    artists = self.includes(albums: [:images, :tracks]).all
    CSV.generate(options) do |csv|
      csv << export_columns
      artists.each do |artist|
        csv << [artist.name, artist.albums.length, artist.albums_years, artist.common_words]
      end
    end
  end
  
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    respond_to do |format|
      format.html { @artists = Artist.includes(albums: [:images, :tracks]) }
      format.csv { send_data Artist.to_csv }
    end
  end

  def show
    @artist = Artist.includes(albums: [:images, :tracks]).find(params[:id])
    respond_to do |format|
      format.html
    end
  end

end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/index.html.erb
<div class="row my-5">
  <div class="col-sm-12 col-md-6 col-lg-3 mb-3">
    <div class="card album">
      <img class="card-img-top" src="<%= @artist.albums.first.images.last.url %>" alt="<%= @artist.albums.first.name %>">
    </div>
  </div>
  <div class="col-sm-12 col-md-6 col-lg-9 mb-3">
    <h1>
      <%= @artist.name %>
    </h1>
    <%= link_to 'Download CSV', artist_path(@artist, format: 'csv') %>
  </div>
</div>

app/views/artists/show.html.erb
<div class="row my-5">
  <div class="col-sm-12 col-md-6 col-lg-3 mb-3">
    <div class="card album">
      <img class="card-img-top" src="<%= @artist.albums.first.images.last.url %>" alt="<%= @artist.albums.first.name %>">
    </div>
  </div>
  <div class="col-sm-12 col-md-6 col-lg-9 mb-3">
    <h1>
      <%= @artist.name %>
    </h1>
    <%= link_to 'Download CSV', artists_path(format: 'csv') %>
  </div>
</div>