config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout', password: 'password', confirmation: 'confirmation', unlock: 'unlock', registration: 'account', sign_up: 'register' }

  resources :albums do
    get '/search', to: 'albums#search', on: :collection
    get '/mine', to: 'albums#mine', on: :collection
  end

  resources :artists

  root to: "marketing#index"
end

app/models/album.rb
class Album < ApplicationRecord

  belongs_to :artist, counter_cache: true

  has_many :tracks
  has_many :images
  has_many :libraries
  has_many :users, through: :libraries

  validates :name,     presence: true
  validates :artist_id, presence: true

  def year
    published.present? ? published.to_time.strftime("%Y").to_i : nil
  end

  def self.search(q)
    return [] unless q.present?
    begin
      response = RestClient.get 'http://ws.audioscrobbler.com/2.0/', {
        params: {
          api_key: ENV['LAST_FM_API_KEY'],
          format: 'json',
          method: 'album.search',
          album: URI.encode(q, /\W/)
        }
      }
    rescue RestClient::Unauthorized, RestClient::Forbidden => err
      puts 'Access denied'
      return nil
    else
      json_response = JSON.parse(response)
      return json_response.dig('results', 'albummatches', 'album')
    end
  end

  def self.lookup(artist_name, album_name)
    return [] unless artist_name.present? and album_name.present?
    begin
      response = RestClient.get 'http://ws.audioscrobbler.com/2.0/', {
        params: {
          api_key: ENV['LAST_FM_API_KEY'],
          format: 'json',
          method: 'album.getInfo',
          artist: artist_name,
          album: album_name
        }
      }
    rescue RestClient::Unauthorized, RestClient::Forbidden => err
      puts 'Access denied'
      return nil
    else
      json_response = JSON.parse(response)
      puts 'Lookup response'
      puts json_response
      puts json_response.dig('album')
      return json_response.dig('album')
    end
  end

  def self.import(album_data)
    return false unless album_data.key?('artist') && album_data.key?('name')

    artist = Artist.find_or_create_by(name: album_data['artist'])

    album = artist.albums.new(name: album_data['name'])
    album.published = album_data.dig('wiki', 'published')
    album.last_fm_url = album_data.dig('url')
    album.save!

    if album_data.key?('image')
      album_data['image'].each do |i|
        album.images.create(url: i['#text']) if i.key?('#text') and i['#text'].present?
      end
    end

    if album_data.dig('tracks', 'track')
      album_data['tracks']['track'].each do |t|
        track = album.tracks.new(name: t['name'])
        track.seconds = t.dig('duration')
        track.last_fm_url = t.dig('url')
        track.order = t.dig('@attr', 'rank')
        track.save!
      end
    end

    album
  end

  def self.find_and_assign(artist_name, album_name, user_id)
    puts 'Running find and assign'
    user = User.find(user_id)
    artist = Artist.find_or_create_by(name: artist_name)
    album = artist.albums.find_by(name: album_name)
    unless album
      puts 'Need to import album'
      album_data = self.lookup(artist_name, album_name)
      puts album_data
      album = self.import(album_data) if album_data
    end
    user.albums << album if album
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!

  def index
    @albums = Album.search(params[:q])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def search
    @albums = Album.search(params[:q])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def mine
    @libraries = current_user.libraries.includes(album: [:artist, :images])
  end

  def create
    Album.find_and_assign(params[:artist], params[:album], current_user.id)
  end

  def show
    @library = current_user.libraries.includes(album: [:artist, :images, :tracks]).find(params[:id])
  end

  def edit
    @library = current_user.libraries.includes(:album).find(params[:id])
  end

  def update
    @library = current_user.libraries.find(params[:id])
    @library.update(state: params[:library][:state])
    respond_to do |format|
      format.html { redirect_to album_path(@library), flash: { success: "You have successfully updated your album." } }
    end
  end

  def destroy
    @library = current_user.libraries.find(params[:id])
    @library.destroy
    respond_to do |format|
      format.html { redirect_to mine_albums_path, flash: { success: "Album has been removed." } }
    end
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
  def cover_art(image=[])
    image_object = image.find{|o| o['size'] == 'extralarge' and o['#text'].present? }
    url = image_object['#text'] if image_object
    url ||= 'https://lastfm-img2.akamaized.net/i/u/174s/c6f59c1e5e7240a4c0d427abd71f3dbb'
  end
end

app/views/albums/_results.html.erb
<% if @albums %>
  <% @albums.each do |a| %>
    <div class="col-sm-12 col-md-6 col-lg-3 mb-3">
      <a href="/albums?album=<%= URI.encode(a['name'], /\W/) %>&artist=<%= URI.encode(a['artist'], /\W/) %>" class="card album" data-remote="true" data-method="post">
        <img class="card-img-top" src="<%= cover_art a['image'] %>" alt="<%= a['name'] %>">
        <div class="card-body">
          <h4 class="card-title"><%= a['name'] %></h4>
          <p class="card-text"><%= a['artist'] %></p>
        </div>
        <span class="add badge badge-primary">Add +</span>
      </a>
    </div>
  <% end %>
<% else %>
  No results found.
<% end %>

app/views/albums/create.js.erb
$('#adding-notice').hide();

app/views/albums/edit.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8 offset-md-2 col-lg-4 offset-lg-4 py-5">

    <h3><%= @library.album.name %></h3>
    <p>
      Edit <%= @library.album.name %>'s condition.
    </p>
    <%= form_for(@library, url: album_path(@library)) do |f| %>

      <div class="form-group">
        <label class="sr-only">Name</label>
        <%= f.select(:state, Library.aasm.states_for_select, {}, { class: 'form-control' }) %>
      </div>

      <button type="submit" class="btn btn-primary">Update</button>

    <% end %>

    <hr>

    <a class="btn btn-outline-danger" rel="nofollow" data-method="delete" href="<%= album_path(@library) %>">Remove Album</a>

  </div>
</div>

app/views/albums/index.html.erb
<div class="row text-center">
  <div class="col py-5">
    <h1>
      Welcome to Artistry
    </h1>
    <p>
      Start adding albums to your collection.
    </p>

    <form action="/albums/search" method="get" data-remote="true">
      <input name="q" type="text" class="form-control form-control-lg" id="search" placeholder="Search for an album or artist">
    </form>

  </div>
</div>

<div id="results" class="row mt-3"></div>

<%= render '/shared/adding_album_notice' %>

app/views/albums/mine.html.erb
<div class="row text-center">
  <div class="col py-5">
    <h1>
      My Albums
    </h1>
  </div>
</div>

<div id="results" class="row mt-3">
  <% if @libraries %>
    <% @libraries.each do |library| %>
      <div class="col-sm-12 col-md-6 col-lg-3 mb-3">
        <a href="<%= album_path library %>" class="card album">
          <img class="card-img-top" src="<%= library.album.images.last.url %>" alt="<%= library.album.name %>">
          <div class="card-body">
            <h4 class="card-title"><%= library.album.name %></h4>
            <p class="card-text"><%= library.album.artist.name %></p>
          </div>
          <span class="add badge badge-primary">View</span>
        </a>
      </div>
    <% end %>
  <% else %>
    No results found.
  <% end %>
</div>

app/views/albums/search.js.erb
$('#results').html('<%= j render("/albums/results") %>');

app/views/albums/show.html.erb
<div class="row my-5">

  <div class="col-sm-12 col-md-6 col-lg-3 mb-3">
    <div class="card album">
      <img class="card-img-top" src="<%= @library.album.images.last.url %>" alt="<%= @library.album.name %>">
    </div>
  </div>

  <div class="col-sm-12 col-md-6 col-lg-9 mb-3">
    <h1>
      <%= @library.album.name %>
    </h1>
    <p>
      <%= link_to @library.album.artist.name, artist_path(@library.album.artist) %> <br>
      <%= @library.album.published %> <br>
      <span class="badge badge-secondary"><%= @library.state.humanize %></span>
    </p>
    <%= link_to 'Edit', edit_album_path(@library), class: 'btn btn-sm btn-outline-dark' %>
    <%= link_to 'View on last.fm', @library.album.last_fm_url, class: 'btn btn-sm btn-outline-dark', target: '_blank' %>
  </div>
</div>

<div class="row mb-5">
  <div class="col">

    <table class="table table-bordered">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Duration</th>
        </tr>
      </thead>
      <tbody>
        <% @library.album.tracks.each do |track| %>
          <tr>
            <td><%= track.order %></td>
            <td><%= link_to track.name, track.last_fm_url, class: 'btn btn-sm btn-link', target: '_blank' %></td>
            <td><%= Time.at(track.seconds).utc.strftime("%M:%S") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>