config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout', password: 'password', confirmation: 'confirmation', unlock: 'unlock', registration: 'account', sign_up: 'register' }

  resources :albums do
    get '/search', to: 'albums#search', on: :collection
    get '/mine', to: 'albums#mine', on: :collection
  end

  resources :artists

  root to: "marketing#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>

    <title>Artistry</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Artistry</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="<%= albums_path %>">Find Albums</a>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link" href="<%= mine_albums_path %>">My Albums</a>
            </li>
          <% end %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= user_signed_in? ? current_user.name : 'Get Started' %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <% if user_signed_in? %>
                <a class="dropdown-item" rel="nofollow" data-method="delete" href="/logout">Log out</a>
              <% else %>
                <a class="dropdown-item" href="/account/register">Create an account</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="/login">Login</a>
              <% end %>
            </div>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">

      <%= notice ? "<div class=\"alert alert-primary mt-3\" role=\"alert\">#{notice}</div>".html_safe : '' %>
      <%= alert ? "<div class=\"alert alert-danger mt-3\" role=\"alert\">#{alert}</div>".html_safe : '' %>

      <%= yield %>

    </div>

    <nav class="navbar navbar-light bg-light mt-5">
      <span class="navbar-text">
        <a href="https://github.com/stephenkey/artistry" target="_blank">View on Github</a>
      </span>
    </nav>





  </body>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>